src/Entity/Questionnaire.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use Serializable;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\QuestionnaireRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass="App\Repository\QuestionnaireRepository", repositoryClass=QuestionnaireRepository::class)
 * @Vich\Uploadable
 */
class Questionnaire implements Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $difficulty;

    /**
     * @ORM\OneToMany(targetEntity=Question::class, mappedBy="questionnaire",
     *     orphanRemoval=true, cascade={"persist"})
     */
    private $questions;

    /**
     * @ORM\OneToMany(targetEntity=Pass::class, mappedBy="questionnaire", orphanRemoval=true)
     */
    private $pass;

    /**
     * @ORM\Column(type="date")
     */
    private $date_creation;

    /**
     * @Assert\File(
     *  mimeTypes = {"image/jpeg", "image/png", "image/svg+xml"},
     *  mimeTypesMessage = "Chargé un image correct - jpeg, png -"
     * )
     * @Vich\UploadableField(mapping="questionnaire_image", fileNameProperty="imageName")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @var \DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * @ORM\ManyToMany(targetEntity=Lesson::class, mappedBy="questionnaires")
     */
    private $lessons;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $creator;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $visibility;

    /**
     * @ORM\Column(type="integer")
     */
    private $realisation_time;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $level;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link_description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $instructions;

    public const DIFFICULTIES = ["cEcrite", "cOrale", "eEcrite", "lexique", "phonetique", "grammaire"];

    public function __construct()
    {
        $this->questions = new ArrayCollection();
        $this->pass = new ArrayCollection();
        $this->lessons = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDifficulty(): ?string
    {
        return $this->difficulty;
    }

    public function setDifficulty(string $difficulty): self
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
            $question->setQuestionnaire($this);
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->contains($question)) {
            $this->questions->removeElement($question);
            // set the owning side to null (unless already changed)
            if ($question->getQuestionnaire() === $this) {
                $question->setQuestionnaire(null);
            }
        }

        return $this;
    }

    public function getPass(): Collection
    {
        return $this->pass;
    }

    public function addPass(Pass $pass): self
    {
        if (!$this->pass->contains($pass)) {
            $this->pass[] = $pass;
            $pass->setQuestionnaire($this);
        }

        return $this;
    }

    public function removePass(Pass $pass): self
    {
        if ($this->pass->contains($pass)) {
            $this->pass->removeElement($pass);
            // set the owning side to null (unless already changed)
            if ($pass->getQuestionnaire() === $this) {
                $pass->setQuestionnaire(null);
            }
        }

        return $this;
    }

    public function getDateCreation(): ?string
    {
        return $this->date_creation->format('d-m-Y');
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getTotalScore(): int
    {
        $total = 0;
        foreach ($this->questions as $question) {
            $total+= $question->getScore();
        }
        return $total;
    }

    /**
     * Method to check if a questionnaire has at list 1 question
     * and the question has at list 2 propositions
     * @return bool
     */
    public function isPlayable(): bool
    {
        if (count($this->questions) === 0) {
            return false;
        }
        return $this->questions->forAll(function ($key, $question) {
            return count($question->getPropositions()) >= 2;
        });
    }

    /**
     * @param  File|UploadedFile|null  $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        // Only change the updated af if the file is really uploaded to avoid database updates.
        // This is needed when the file should be set when loading the entity.
        if ($this->imageFile instanceof UploadedFile) {
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->imageName,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->imageName,
            ) = unserialize($serialized, array('allowed_classes' => false));
    }

    /**
     * @return Collection|Lesson[]
     */
    public function getLessons(): Collection
    {
        return $this->lessons;
    }

    public function addLesson(Lesson $lesson): self
    {
        if (!$this->lessons->contains($lesson)) {
            $this->lessons[] = $lesson;
            $lesson->addQuestionnaire($this);
        }

        return $this;
    }

    public function removeLesson(Lesson $lesson): self
    {
        if ($this->lessons->removeElement($lesson)) {
            $lesson->removeQuestionnaire($this);
        }

        return $this;
    }

    public function getCreator(): ?string
    {
        return $this->creator;
    }

    public function setCreator(string $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    public function getVisibility(): ?bool
    {
        return $this->visibility;
    }

    public function setVisibility(bool $visibility): self
    {
        $this->visibility = $visibility;

        return $this;
    }

    public function getRealisationTime(): ?int
    {
        return $this->realisation_time;
    }

    public function setRealisationTime(int $realisation_time): self
    {
        $this->realisation_time = $realisation_time;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function setLevel(string $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getLinkDescription(): ?string
    {
        return $this->link_description;
    }

    public function setLinkDescription(?string $link_description): self
    {
        $this->link_description = $link_description;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getInstructions(): ?string
    {
        return $this->instructions;
    }

    public function setInstructions(?string $instructions): self
    {
        $this->instructions = $instructions;

        return $this;
    }
}

src/Form/QuestionnaireType.php
<?php

namespace App\Form;

use App\Entity\Questionnaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class QuestionnaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add(
                'title',
                TextType::class,
                [
                    'purify_html' => true,
                    'label' => 'Titre',
                ]
            )
            ->add(
                'instructions',
                TextareaType::class,
                [
                    'label' => 'Consigne',
                    'required' => false,
                ]
            )
            ->add(
                'imageFile',
                VichImageType::class,
                [
                    'label' => 'Choisissez votre image :',
                    'allow_delete' => false,
                    'imagine_pattern' => 'questionnaire',
                    'required' => false,
                ]
            )
            ->add(
                'link_description',
                TextType::class,
                [
                    'purify_html' => true,
                    'label' => 'Description du lien',
                    'required' => false,
                ]
            )
            ->add(
                'link',
                TextType::class,
                [
                    'purify_html' => true,
                    'label' => 'Lien',
                    'constraints' => [
                        new Regex(
                            [
                                'pattern' => '$https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)?$',
                                'message' => 'Votre lien doit commencer avec http:// ou https:// et doit finir avec un pointquelquechose.',
                            ]
                        ),
                    ],
                    'attr' => [
                        'placeholder' => 'ex: https://contact-promotion.org',
                    ],
                    'required' => false,
                ]
            )
            ->add(
                'difficulty',
                ChoiceType::class,
                [
                    'choices' => [
                        'Compréhension écrite' => 'cEcrite',
                        'Compréhension orale' => 'cOrale',
                        'Expression écrite' => 'eEcrite',
                        'Lexique' => 'lexique',
                        'Phonétique' => 'phonetique',
                        'Grammaire' => 'grammaire',
                    ],
                    'label' => 'Catégorie',
                ]
            )
            ->add(
                'level',
                ChoiceType::class,
                [
                    'choices' => [
                        'Alpha 1' => 'Alpha1',
                        'Alpha 2' => 'Alpha2',
                        'A1.1' => 'A1.1',
                        'A1' => 'A1',
                        'A2' => 'A2',
                        'B1' => 'B1',
                        'B2' => 'B2',
                        'CléA' => 'CléA',
                        'Voltaire' => 'Voltaire',
                    ],
                    'label' => 'Niveau',
                ]
            )
            ->add(
                'type',
                ChoiceType::class,
                [
                    'choices' => [
                        'QCM ' => 'qcm',
                        'Vrai/faux 2' => 'vf',
                        'Texte à trous' => 'trous',
                    ],
                    'label' => 'Type d\'activité',
                ]
            )
            ->add(
                'realisation_time',
                ChoiceType::class,
                [
                    'choices' => [
                        '2 min' => 2,
                        '5 min' => 5,
                        '10 min' => 10,
                        '15 min' => 15,
                        '20 min' => 20,
                        '30 min' => 30,
                    ],
                    'label' => 'Temps de realisation',
                ]
            )
            ->add(
                'visibility',
                CheckboxType::class,
                [
                    'label' => 'Rendre visible',
                    'required' => false,
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(
            [
                'data_class' => Questionnaire::class,
            ]
        );
    }
}

templates/questionnaire/_form.html.twig
{{ form_start(form) }}

{{ form_row(form.title) }}
{{ form_row(form.type) }}
{{ form_row(form.instructions) }}

{% set error_flag = form_errors(form.imageFile) %}
<label class=" {% if error_flag %}has-error{% endif %}">
	Image
</label>
{{ form_widget(form.imageFile) }}
{% if error_flag %}
	<div class="has-error">
		{{ form_errors(form.imageFile) }}
	</div>
{% endif %}

{{ form_row(form.link_description) }}
<div class="d-flex align-items-end">
	{{ form_row(form.link) }}
	<div class="alert alert-info ml-4" role="alert">
		Votre lien doit commencer avec http:// ou https:// et doit finir avec un pointquelquechose.
	</div>
</div>

{{ form_row(form.difficulty) }}
{{ form_row(form.level) }}

<div class="d-flex align-items-end">
	{{ form_row(form.realisation_time) }}
	<div class="alert alert-info ml-4" role="alert">
		Indiquez ici combien de temps votre apprenant·e aura besoin pour realiser cette activité.
	</div>
</div>

<div class="d-flex align-items-end">
	{{ form_row(form.visibility) }}
	<div class="alert alert-info ml-4" role="alert">
		{% if questionnaire.lessons|length > 0 %}
			Cette action rendra visible votre activité dans votre module et dans la boîte à outils.
		{% else %}
			Cette action rendra visible votre activité dans la boîte à outils.
		{% endif %}
	</div>
</div>
<button type="submit" class="btn btn-primary">{{ button|default('Create') }}</button>
{{ form_end(form) }}

templates/questionnaire/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Éditer une activité
{% endblock %}

{% block body %}
	<div class="row mt-4 mb-5">
		<div class="col-10 offset-1">
			<h3>Éditer l'activité</h3>
			{{ include('questionnaire/_form.html.twig', {form: form, button: 'Éditer'}) }}
		</div>
	</div>
{% endblock %}

templates/questionnaire/index.html.twig
{% extends "base.html.twig" %}

{% block title %}Liste des activités
{% endblock %}

{% block body %}
	<div class="row mt-4">
		<div class="col-5 offset-1">
			{{ form_start(form) }}
			<div class="form-group">
				{{ form_errors(form.title) }}
				{{ form_widget(form.title) }}
				{{ form_help(form.title) }}
			</div>
			<div class="form-group">
				{{ form_errors(form.level) }}
				{{ form_widget(form.level) }}
				{{ form_help(form.level) }}
			</div>
			<div class="form-group">
				{{ form_errors(form.category) }}
				{{ form_widget(form.category) }}
				{{ form_help(form.category) }}
			</div>
		</div>
		<div class="col-5">
				<div class="form-group">
					{{ form_errors(form.author) }}
					{{ form_widget(form.author) }}
					{{ form_help(form.author) }}
				</div>
				<div class="form-group d-flex justify-content-between">
					{{ form_errors(form.date) }}
					{{ form_widget(form.date) }}
					{{ form_help(form.date) }}
					{{ form_widget(form.submit) }}
				</div>
			{{ form_end(form) }}
		</div>
	</div>

	<div class="row mt-5">
		<div class="col-10 offset-1">
			<div class="d-flex justify-content-between align-items-center">
				<h3>Liste des activités</h3>
				{% if lesson_id is null %}
					<a href="{{ path('questionnaire_new') }}" class="btn btn-primary mb-2" role="button">Créer nouvelle</a>
				{% endif %}
			</div>

			<table class="table border-bottom mt-2">
				<thead class="thead-dark">
					<tr>
						<th scope="col"></th>
						<th scope="col">Titre</th>
						<th scope="col">Auteur·rice</th>
						<th scope="col">Niveau</th>
						<th scope="col">Catégorie</th>
						<th scope="col">Date de création</th>
						<th scope="col"></th>
					</tr>
				</thead>
				<tbody>
					{% for questionnaire in questionnaires %}
						{% if questionnaire.lessons|length > 1 %}
							<tr class="table-warning">
							{% elseif questionnaire.visibility %}
								<tr class="table-success">
								{% else %}
									<tr>
									{% endif %}
									<th scope="row"></th>
									<td>
										{% if classroom_id is not null and (lonely is defined and lonely is not null) %}
											<a href="{{ path('questionnaire_show', {id: questionnaire.id, lesson_id: lesson_id, classroom_id: classroom_id, lonely: lonely}) }}">
												{{ questionnaire.title }}
											</a>
										{% elseif list is not null %}
											<a href="{{ path('questionnaire_show', {id: questionnaire.id, lesson_id: lesson_id, list: list, extra: extra}) }}">
												{{ questionnaire.title }}
											</a>
										{% else %}
											<a href="{{ path('questionnaire_show', {id: questionnaire.id, lesson_id: lesson_id}) }}">
												{{ questionnaire.title }}
											</a>
										{% endif %}
									</td>
									<td>{{ questionnaire.creator }}</td>
									<td>{{ questionnaire.level }}</td>
									<td>{{ questionnaire.difficulty }}</td>
									<td>{{ questionnaire.dateCreation }}</td>
									<td>
										{% if (is_granted('ROLE_ADMIN') or app.user.username == questionnaire.creator) and lesson_id is null %}
											<a href="{{ path('questionnaire_edit', {id: questionnaire.id}) }}" {% if questionnaire.lessons|length > 1 %} id="editerInList" {% endif %} class="btn btn-secondary mb-2" role="button">Éditer</a>
											{% if questionnaire.lessons|length > 1 %}
												<form method="post" action="{{ path('questionnaire_delete', {id: questionnaire.id}) }}" style="display: inline-block" onsubmit="return confirm('Attention cette activité est utilisée dans d\'autres modules.\nSi vous la supprimez, elle sera également supprimée de ces autres modules.')">
												{% else %}
													<form method="post" action="{{ path('questionnaire_delete', {id: questionnaire.id}) }}" style="display: inline-block" onsubmit="return confirm('Êtes vous sur·e de vouloir supprimer cette activité ? \nCette action est irréversible.')">
													{% endif %}
													<input type="hidden" name="_method" value='DELETE'>
													<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ questionnaire.id) }}">
													<button class="btn btn-danger mr-2">Supprimer</button>
												</form>
											{% endif %}
											{% if lonely is defined and lonely is not null %}
												<a href="{{ path('lesson_questionnaire_add', {id: lesson_id, questionnaire_id: questionnaire.id, classroom_id: classroom_id, lonely: lonely}) }}" class="btn btn-secondary mb-2" role="button">Ajouter</a>
											{% elseif list is defined and list is not null %}
												<a href="{{ path('lesson_questionnaire_add', {id: lesson_id, questionnaire_id: questionnaire.id, list: list}) }}" class="btn btn-secondary mb-2" role="button">Ajouter</a>
											{% endif %}
										</td>
								</tr>
							{% else %}
							<tr>
								<td colspan="6">Pas de resultat trouvé</td>
							</tr>
						{% endfor %}
						</tbody>
					</table>
					<div class="pagination">
						{{ knp_pagination_render(questionnaires) }}</div>
			</div>
		</div>
	{% endblock %}

templates/questionnaire/jouer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quiz-jouer{% endblock %}

{% block body %}

{% endblock %}

templates/questionnaire/new.html.twig
{% extends "base.html.twig" %}

{% block title %}Créer une activité
{% endblock %}

{% block body %}
	{% if lesson_id is not null %}
		<div class="row mt-4">
			<div class="col-12 d-flex justify-content-center">
				{% if lonely is defined and lonely is not null %}
					<a href="{{ path('questionnaire_index', {lesson_id: lesson_id, classroom_id: classroom_id, lonely: lonely}) }}" class="btn btn-secondary">importer activité existante</a>
				{% elseif list is not null and classroom_id is null%}
					<a href="{{ path('questionnaire_index', {lesson_id: lesson_id, classroom_id: classroom_id, list:list, extra: true}) }}" class="btn btn-secondary">importer activité existante</a>
				{% endif %}
			</div>
		</div>
	{% endif %}


	{% if lesson_id is not null %}
		<div class="row mt-3 mb-5">
		{% else %}
			<div class="row mt-4 mb-5">
			{% endif %}
			<div class="col-10 offset-1">
				<h3>Créer une activité</h3>
				{{ include('questionnaire/_form.html.twig', {form: form, button: 'Créer'}) }}
			</div>
		</div>
	{% endblock %}

templates/questionnaire/play.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ questionnaire.title }}
{% endblock %}

{% block body %}
	<div class="row mt-4">
		<div class="col-10 offset-1">
			<h3>
				{{ questionnaire.title }}
			</h3>

			{% if questionnaire.instructions %}
				<p class="alert alert-info">{{ questionnaire.instructions }}</p>
			{% endif %}


			<div class="d-flex flex-column align-items-center">
				{% if questionnaire.linkdescription %}
					<div class="d-flex align-items-center m-3">
						<img src="{{ asset('images/link-icon.webp') }}" alt="link icon" class="link-icon mr-3">
						<a href="{{ questionnaire.link }}" target="_blank" rel="noopener noreferrer" class="play-link">{{ questionnaire.linkdescription }}</a>
					</div>
				{% endif %}
				{% if vich_uploader_asset(questionnaire, 'imageFile') %}
					<img src="{{ vich_uploader_asset(questionnaire, 'imageFile') | imagine_filter('questionnaire')}}" alt="Image" class="m-3">
				{% endif %}
			</div>

			{% if finalResults['given'] is not null %}
				<div class="alert alert-primary mt-3">Vos points :
					{{ points }}
					/
					{{ questionnaire.totalScore }}</div>
			{% endif %}
		</div>
	</div>

	<div class="row">
		<div class="col-10 offset-1">
			<form method="post">
				{% for question in questions %}
					<h5 class="pt-3">{{ loop.index }}
						-
						{{ question.title }}</h5>

					{% if question.imageName is defined and question.imageName is not null %}
						<div class="m-4 text-center">
							<img src="{{ vich_uploader_asset(question, 'imageFile') | imagine_filter('question') }}" alt="profile">
						</div>
					{% endif %}

					<small class="text-muted">{{ question.score }}
						{{ question.score > 1 ? "points" : "point" }}</small>

					<ul class="list-group mb-4">
						{% for proposition in question.propositions %}

							{% set lgi_class, checked = "", "" %}
							{% if finalResults['given'] is not null and proposition.id in finalResults['given'] %}
								{% set checked = "checked" %}
								{% if proposition.id in finalResults['rights'] %}
									{% set lgi_class = "correct" %}
								{% else %}
									{% set lgi_class = "wrong" %}
								{% endif %}
							{% endif %}

							<li class="list-group-item {{ lgi_class }}">
								<label>
									<input type="radio" name="{{ question.id }}" value="{{ proposition.id }}" {{ checked }}>
									{{ proposition.text }}
								</label>
							</li>
						{% endfor %}
					</ul>
				{% endfor %}
			</div>
		</div>

		<div class="pagination">
			{{ knp_pagination_render(questions) }}
		</div>


		{% if count < 10 %}
			<footer class="text-center mt-3">
				<button class="btn btn-primary" type="submit">
					<i class="fas fa-check"></i>&nbsp;Je valide mes réponses
				</button>
			</footer>
		{% endif %}

	</form>
{% endblock %}